# yamllint disable rule:line-length
version: 2.1

setup: << pipeline.parameters.run-setup-workflow >>

parameters:
  run-setup-workflow:
    default: true
    type: boolean
  run-orb-workflow:
    default: false
    type: boolean

orbs:
  circleci-cli: circleci/circleci-cli@volatile
  path-filtering: circleci/path-filtering@0.1.3
  vrsn: thaffenden/vrsn@volatile

ignore-main: &ignore-main
  filters:
    branches:
      ignore:
        - main

jobs:
  push-dev-tagged-orb:
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: publish dev tagged orb
          command: circleci orb publish ./.circleci/orb.yml thaffenden/vrsn@dev:$CIRCLE_BRANCH --token $CIRCLECI_ORB_API_TOKEN

  push-live-tagged-orb:
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: publish live orb
          command: |
            VERSION=$(head -n 1 VERSION)
            circleci orb publish ./.circleci/orb.yml "thaffenden/vrsn@$VERSION" --token $CIRCLECI_ORB_API_TOKEN

  validate-orb:
    executor: circleci-cli/default
    steps:
      - checkout
      - run:
          name: validate orb
          command: circleci orb validate ./.circleci/orb.yml

workflows:
  setup:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-setup-workflow >>]
    jobs:
      - vrsn/check-version:
          <<: *ignore-main
      - path-filtering/filter:
          config-path: .circleci/config.yml
          mapping: |
            .* run-setup-workflow false
            .circleci/.* run-orb-workflow true

  orb-test-and-release:
    when:
      and:
        - equal: [true, << pipeline.parameters.run-orb-workflow >>]
    jobs:
      - validate-orb
      - push-dev-tagged-orb:
          <<: *ignore-main
          requires:
            - validate-orb
      - push-live-tagged-orb:
          filters:
            branches:
              only:
                - main
          requires:
            - validate-orb
